name: elementarypos_office
description: "Elementary POS Ofiice."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.6
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/l10n/